# Generated by Django 5.2.8 on 2025-12-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='upsdated_at',
            new_name='updated_at',
        ),
    ]
